version: '3'
services:
  app:
    container_name: espaco-divas-app
    image: astrotechdevs/php-nginx:latest
    working_dir: /app
    volumes:
      - ./:/app
      - ./.docker/crontab:/etc/cron.d/custom-crontab
    ports:
      - '8080:80'
    networks:
      - espaco-divas-network
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8
    container_name: espaco-divas-db
    command: [
      'mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--wait_timeout=28800',
      '--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
      '--log_bin_trust_function_creators=1',
      '--sort_buffer_size=10485760' #10MB
    ]
    restart: always
    ports:
      - "33089:3306"
    environment:
      - TZ=${APP_TIMEZONE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    networks:
      - espaco-divas-network
    volumes:
      - ./.docker/data:/var/lib/mysql
      - ./.docker/dumps:/var/dumps

  redis:
    image: redis:6.2.6
    container_name: espaco-divas-redis
    environment:
      - TZ=${APP_TIMEZONE}
    volumes:
      - ./.docker/redis:/data
    ports:
      - "6379:6379"
    networks:
      - espaco-divas-network
    depends_on:
      - db

networks:
  espaco-divas-network:
    driver: bridge
